config/routes.rb
Rails.application.routes.draw do

  root 'pets#index'

  resources :owners do
    resources :pets
  end

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :pets, :dependent => :destroy
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/owners_controller.rb
require 'owners/owner_factory'
require 'owners/entity/owner_entity'

class OwnersController < ApplicationController

  def index
    context = Owners::OwnerFactory.find_all_owners
    @owners = context.execute
  end

  def new
    @owner = Owners::Entity::OwnerEntity.new(args = {})
  end

  def create
    owner_context = Owners::OwnerFactory.create_owner
    owner_context.execute(owner_params)
    redirect_to owners_path
  end

  private

  def owner_params
    params.permit(:name, pets_attributes: [:name, :owner_id, :type_of_animal])
    #params.require(:screenshot).permit(:title, :assets_attributes => [:filename, :id, :screenshot_id])
  end

end

app/controllers/pets_controller.rb
require 'pets/pet_factory'
require 'pets/entity/pet_entity'

class PetsController < ApplicationController

  def index
    context = Pets::PetFactory.find_all_pets
    @pets = context.execute
  end

  def new
    @pet = Pets::Entity::PetEntity.new(args = {})
  end

  def create
    context = Pets::PetFactory.create_pet
    context.execute(pet_params)
    redirect_to pets_path
  end

  private

  def pet_params
    params.permit(:name, :owner_id, :type_of_animal)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/animals/index.html.erb
<article class="container">
<div class="col-xs-12">
  <%= link_to 'Add an Animal', new_animal_path, class: 'btn btn-primary' %>
  <br/><br/>

  <h3>All Animals</h3>

  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
      </tr>
    </thead>

    <tbody>
      <% @animals.each do |animal| %>
        <tr>
          <td data-field="animal.id"><%= animal.id %></td>
          <td data-field="animal.name"><%= animal.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>
</article>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= form_tag(animals_path, method: 'post') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <br>

   <div><%= submit_tag 'Save' %></div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConstructorPattern</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/index.html.erb
<article class="container">
<div class="col-xs-12">
  <%= link_to 'Add an Owner', new_owner_path, class: 'btn btn-primary' %>
  <br/><br/>

  <h3>All Owners</h3>

  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
      </tr>
    </thead>

    <tbody>
      <% @owners.each do |owner| %>
        <tr>
          <td data-field="owner.id"><%= owner.id %></td>
          <td data-field="owner.name"><%= owner.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>
</article>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<form action='/owners' method="POST">
  
  <% 5.times do %>
    <fieldset>
      <li>
      <label>Name</label>
      <input name="owners[][Pet Name]"/>
      </li>
      <li>
      <label>Difficulty</label>
      <input name="owners[][difficulty]" />
      </li>
      <li>
      <label>Players</label>
      <input name="owners[][players]" />
      </li>
    </fieldset>
  <% end %>
  <input type="submit"/>
</form>